exclude: ^LICENSE/|\.(pickle|ipynb)$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: debug-statements
        language_version: python3
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        require_serial: true
        types_or: [python, pyi]
        additional_dependencies: [black==23.7.0]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.285
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.8
    hooks:
      - id: vulture
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
